### ISSUE TITLE
Plugin suddenly stopped working on April 1st

### ISSUE THREAD

**Issue by Jarvichi** [jonathan-fielding/homebridge-yalealarmsystem#3]
My Homebridge suddenly stopped working yesterday, looking at the log file it appears to be the Yale Alarm plugin that is throwing the error. (See attached log - in reverse order - sorry)

 code: 'ENETUNREACH' }
  errno: 'ENETUNREACH',
  type: 'system',
  message: 'request to https://www.yalehomesystem.co.uk/homeportal/api/login/check_login failed, reason: connect ENETUNREACH 88.208.250.60:443 - Local (0.0.0.0:0)',
  name: 'FetchError',
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at TLSSocket.emit (events.js:211:7)
    at emitOne (events.js:116:13)
    at TLSSocket.socketErrorListener (_http_client.js:387:9)
    at ClientRequest.emit (events.js:211:7)
    at emitOne (events.js:116:13)
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/homebridge-yalealarmsystem/node_modules/node-fetch/index.js:133:11)
{ FetchError: request to https://www.yalehomesystem.co.uk/homeportal/api/login/check_login failed, reason: connect ENETUNREACH 88.208.250.60:443 - Local (0.0.0.0:0)
  code: 'ENETUNREACH' }
  errno: 'ENETUNREACH',
  type: 'system',
  message: 'request to https://www.yalehomesystem.co.uk/homeportal/api/login/check_login failed, reason: connect ENETUNREACH 88.208.250.60:443 - Local (0.0.0.0:0)',
  name: 'FetchError',
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at TLSSocket.emit (events.js:211:7)
    at emitOne (events.js:116:13)
    at TLSSocket.socketErrorListener (_http_client.js:387:9)
    at ClientRequest.emit (events.js:211:7)
    at emitOne (events.js:116:13)
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/homebridge-yalealarmsystem/node_modules/node-fetch/index.js:133:11)
{ FetchError: request to https://www.yalehomesystem.co.uk/homeportal/api/login/check_login failed, reason: connect ENETUNREACH 88.208.250.60:443 - Local (0.0.0.0:0)

**Comment by jonathan-fielding** [comment]
Closing as old issue
